### ISSUE TITLE
External Security Audit

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#100]
We should hire someone unrelated to this library to audit it for security/cryptography bugs. Here are some of our options (thanks to @zooko for advice):
- NCC (formerly iSEC) used to give discounts for open source. We should approach them. I have a contact from when they sponsored the underhanded crypto contest, so I'll do that.
- OTF's red team. They usually audit OTF-funded projects, but at the very least the people that are part of that team might be interested.
- Matt Green and the TrueCrypt Audit project. They might have funds and/or auditor-power.

In order to convince any of these organizations that it's worth auditing this code for free or at a discount, we need to demonstrate that it's widely used and widely recommended. The v2.0 code that we actually want audited currently isn't, but the old code is, so I think that's good enough. If you know of projects that use this library, or instances of it being recommented by respected/famous people, please mention them in the comments.

I really want to pay the auditor for their work, since I think it will get us a more thorough audit. I'm willing to chip in a bit, but we should explore crowdfunding options.

(I'm putting this in the v2.0 milestone, but that doesn't mean releasing v2.0 should block on the audit.)

**Comment by defuse** [comment]
Remember to ask the auditor about our exception handler hack, and see if they have any better ideas.

**Comment by wilsonge** [comment]
It would be nice to see this from a @joomla leadership perspective. We're currently working on a new major version that will drop php 5.3 support and would be nice to move to an audited v2 version of this as it's worked really well so far in the cms!

**Comment by heliosbryan** [comment]
Is funding an obstacle to an external audit? If so, is donation based funding an option? As a PHP developer I'd personally throw in at least $20 toward this goal. Hopefully with more exposure (like Paragon Initiative articles), other PHP devs will realize the value here and be kind enough to contribute.

**Comment by paragonie-scott** [comment]
Hard to say, really; I haven't gotten any quotes from any of the other firms I asked.

**Comment by defuse** [comment]
I think a 1 or 2 day audit by one person would be enough so we'd be looking at around $1000. I'll ask around once I get time.

**Comment by defuse** [comment]
I kicked this out of the v2.0 release milestone since I don't want it to block the release.

**Comment by defuse** [comment]
I'll leave this issue open, but I don't expect to make progress on it. I might tweet about it but I don't really have funds for a proper audit. I have lots of confidence our internal audit will be good. :-)

**Comment by chris001** [comment]
I'm looking at this for possible addition to suitecrm, for the purposes of symetrically encrypting certain data fields which contain sensitive information such as social security number, financial or banking info, personal health info from health test results, etc.
Any suggestion or example code, on how to achieve a simple encryption of an arbitrary length database field, usually a string.
Of particular concern would be, how to store the key so that an evil sys admin with root access, or a hacker, couldn't make a backup of the file folder, make a mysqldump of the database, take them home, and be able to decrypt any encrypted field in the database.
Previous implementation in sugarcrm was blowfish and vulnerable to just such an attack.  It stored the default key on the filesystem in the document root of the web app. Too easy for an evil sysadmin, or a hacker, to be able to decrypt all private information they wanted.... Definitely a PCI and HIPAA fail!

**Comment by paragonie-scott** [comment]
> Of particular concern would be, how to store the key so that an evil sys admin with root access, or a hacker, couldn't make a backup of the file folder, make a mysqldump of the database, take them home, and be able to decrypt any encrypted field in the database.

As good as this library is, it's the wrong tool for the job in that threat model. What you need is asymmetric-key cryptography, where you can encrypt online (using the public key) but need an offline private key to decrypt anything.

If you soften the requirements a bit (maybe not "root on the server" but "managed to leak the database but cannot read arbitrary files from the filesystem") you can work it out with symmetric-key cryptography (which is what this library provides).

If you want to go the asymmetric route, [EasyRSA](https://github.com/paragonie/EasyRSA) offers hybrid encryption (using RSA for public-key encryption, unfortunately, because that's what PHP provides-- in addition to *this library* for symmetric-key encryption).

Specifically: it generates a random AES key, encrypts your message with defuse (AES-CTR then HMAC-SHA2), and then encrypts the AES key using the long-term RSA public key.

If you're skeptical of the long-term security of RSA against index calculus attacks and/or just want all around better security, [libsodium](https://github.com/jedisct1/libsodium) is excellent and [Halite](https://github.com/paragonie/halite) aspires to be a non-expert- and developer-friendly interface.

In the interest of full disclosure, most of the projects mentioned in this comment are ones I've contributed to in some capacity, so please weigh this advice appropriately. There may be others that are good too.

**Comment by Schnoffel** [comment]
What is the current state of the Security Audit? Did you find someone for this? Are further donations needed?

**Comment by defuse** [comment]
The library still hasn't been audited by anyone other than the authors. If we had a company or group of people willing to put up $5,000-$10,000 we could make it happen, but at the moment I'm too busy with schoolwork to organize something like that (anyone listening is welcome to do so and then just full-disclosure the results).

**Comment by chris001** [comment]
@defuse 
I'd suggest starting a https//www.gofundme.com page, 
or a https://www.bountysource.com/

**Comment by chris001** [comment]
I posted this to bountysource.com where contributors can add money to get this security audit done.
https://www.bountysource.com/issues/27471151-external-security-audit
Financial Backers, go to the link above, enter the dollar amount you contribute, and click the green check button.

**Comment by Schnoffel** [comment]
From $1,000 it went up to $5,000–$10,000 which makes it not so easy.

Aside from this the question is: Do we really need an external security audit?

The code is open source and there are many people out there. I think the proof of security will come automatically when Version 2 is used very often and a long time. When we do an external security audit for $5,000 or more we do not have the evidence it is 100 % secure.

Maybe a not-free security audit would be contra productive as it would cause wrong security in our heads.

**Comment by defuse** [comment]
Closing because I'm not able to invest time into this. I went to extreme lengths to make sure this library is incredibly-well tested and reviewed it like crazy so I don't think this is worth doing anymore.
