### ISSUE TITLE
Recommened Version

### ISSUE THREAD

**Issue by indytechcook** [defuse/php-encryption#159]
First I want to thank you for your fantastic work. 

With version 2 coming out "soon" and version 1.2.1 quite a bit different then master, what version do you currently recommend for use in production?

Stay awesome!

**Comment by paragonie-scott** [comment]
Version 1.2.1 is fine for general purpose string encryption, for up to about 2^64 messages before per encryption key. (You probably won't hit this limit.) See #158 for details.

Version 2.0.0 will offer an interface (`Crypto::legacyDecrypt()`) to decrypt legacy ciphertexts, so even if you commit to 1.2.1 for now and 2.0.0 comes out immediately after, you can transition between the two.

If you have a regulatory obligation to use AES256, wait for version 2 instead of fiddling with the constants yourself.

If you're encrypting files, you'll probably want to wait until version 2 comes out.

Otherwise, 1.2.1 is secure and reliable.

**Comment by indytechcook** [comment]
Thanks @paragonie-scott for the quick and very helpful response.   I'm encrypting private data (SSN and Job History/Salary info) but only in transit along with TLS with client certificates between hosts.  All the private data will be stored in https://www.truevault.com/.

My needs are simple so I'll stick with 1.2.1 for now and add in your bin2hex functions for encoding/decoding the key.

Thanks again for your help!  Keep making a difference.

**Comment by paragonie-scott** [comment]
https://github.com/defuse/php-encryption/releases/tag/v2.0.0 is now available.
