### ISSUE TITLE
key based on password

### ISSUE THREAD

**Issue by robstoll** [defuse/php-encryption#161]
Hi, 

I have the following scenario: 
- data is saved encrypted in DB
- key for encryption must not be saved directly on the system (in clear text)
- yet, application needs the key to decrypt the data
- hence key shall be saved encrypted based on the users password

therefore I would like to know, how can I generate a key passed on a users password?

Cheers,
Robert

**Comment by sarciszewski** [comment]
[`hash_pbkdf2()`](https://secure.php.net/hash_pbkdf2).

**Comment by robstoll** [comment]
and how can I use the generated key with hash_pdkdf2 with your Crypto::encrypt()?

**Comment by sarciszewski** [comment]
```php
$key = hash_pbkdf2(
    'sha256',
    $YOUR_USERS_PASSWORD_HERE,
    $A_HARD_CODED_PASSWORD_MADE_OF_32_RANDOM_BYTES_UNIQUE_PER_USER,
    100000, // minimum 86000
    16,
    true
);

$cipher = Crypto::encrypt($message, $key);
$plain = Crypto::decrypt($cipher, $key);

var_dump($message === $cipher); // bool(true)
```

**Comment by sarciszewski** [comment]
Also, you want to use a CSPRNG for the salt. `Crypto::createRandomKey()` returns 16 bytes. That should be acceptable. Store that long-term per user.

**Comment by robstoll** [comment]
Thanks for the quick reply. I should have mentioned that I am using version 2.x of your library. Crypto::encrypt incorporates the following check:
{code}
if (!is_a($key, "\Defuse\Crypto\Key")) {
            throw new Ex\CannotPerformOperationException(
                "The given key is not a valid Key object."
            );
        }
{code}
Hence I need to transform the key generated by hash_pbkdf2 into a \Defuse\Crypto\Key somehow. 
Any idea?

**Comment by sstok** [comment]
Use `Key::saveToAsciiSafeString` to convert to the Key object to a string for storing, then use `Key::LoadFromAsciiSafeString` to convert the stored string back to a Key object.

**Comment by robstoll** [comment]
@sstok I saw this functionality but it does not help me since I generate the key with hash_pbkdf2 which returns a string (or raw binary data).

**Comment by robstoll** [comment]
For now I am using the method I added in pull request #163 
Please let me know if there is a better way to do this without breaking backward compatibility

**Comment by pnowosie** [comment]
What you need is a long planed feature #5, not implemented yet in v2.0. Maybe your's PR will push things forward a little.

**Comment by SkynetHome** [comment]
I am looking to use this library in a project I am working on but am stuck on the proper storage and usage of keys as well. I have scripts receiving strings of data from users on Android and iOS and I need to encrypt that data and store it in mysql. The data submitted by one user needs to be available to certain other users so I don't think encrypting with a users password will work. Most importantly the data needs to be absolutely secure and absolutely unreadable by me the only DBA. What would be the best approach for storing a key so that PHP can encrypt and decrypt POST and GET requests as needed without giving me any possible access to the data stored on my server.

**Comment by defuse** [comment]
Revisit this when rewriting documentation #52
