### ISSUE TITLE
Hard-coded hash method name in Core::hashEquals()

### ISSUE THREAD

**Issue by pnowosie** [defuse/php-encryption#236]
Is it intentional [here](https://github.com/defuse/php-encryption/blob/v2.0/src/Core.php#L212-L213) to not using const 'HASH_FUNCTION_NAME'?

**Comment by paragonie-scott** [comment]
No, that was an oversight.

**Comment by defuse** [comment]
Yes, it's intentional. `Core::HASH_FUNCTION_NAME` is for the hash function used in the crypto stuff that affects the protocol (the HMAC, the KDF, PBKDF2, etc.). This one has no effect on the protocol itself, it's just a way to compare strings in constant-time.

But I'm going to change it to `Core::HASH_FUNCTION_NAME` since in the hypothetical world where SHA256 is completely broken, we'd want this function to be using whichever more-secure hash we update to.

**Comment by defuse** [comment]
Done. Thanks!
