### ISSUE TITLE
Doc Review: docs/UpgradingFromV1.2.md

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#253]
Review `docs/UpgradingFromV1.2.md` for correctness as well as understandability.

**Comment by larowlan** [comment]
Looks good. One question? Are the old keys no longer compatible? e.g. what happens if the old key cannot be updated - is it ok to continue using the old one? If so should we word it something like so:

```
We recommend updating the key at the same time, however if you cannot ....
```
If the legacy key is invalid, what exception would be thrown? Should we note that?
That would allow someone to attempt an automated upgrade using the existing key, catch an exception and then derive a new key.

**Comment by paragonie-scott** [comment]
> Are the old keys no longer compatible?

Nope.

* Version 1.2.: `$key` is a `string` that is `16` bytes long.
* Version 2.0: `$key` is an `object` that internally stores a `32` byte string.

You'll need fresh keys.

**Comment by larowlan** [comment]
:+1:
thanks

**Comment by defuse** [comment]
I improved the upgrade docs a bit: https://github.com/defuse/php-encryption/blob/v2-add-documentation/docs/UpgradingFromV1.2.md

**Comment by defuse** [comment]
@larowlan: What do you think of the improved version? Is that clear enough, do you think there's any way it could be made more clear? Thanks!

**Comment by larowlan** [comment]
:+1: looks great - thanks

**Comment by paragonie-scott** [comment]
Since this has been reviewed, I'm closing it. @larowlan thanks for your feedback on the documentation! :D
