### ISSUE TITLE
Loading 'Error' class in global scope

### ISSUE THREAD

**Issue by mi6crazyheart** [defuse/php-encryption#273]
HI,
Recently I've upgraded to 2.0 version of your library & I've encountered a strange issue with it. 

It's loading one "Error" class in the global scope. So, whenever I'm including my own 'Error' class file after "require "**./vendor/autoload.php**" it's showing Error "Cannot redeclare class Error".

Here is my Stackoverflow post regarding this - http://stackoverflow.com/questions/37392868/php-composer-auto-load-error

**Comment by paragonie-scott** [comment]
> So, whenever I'm including my own 'Error' class file after "require "./vendor/autoload.php" it's showing Error "Cannot redeclare class Error".

[Read the PHP 7 migration guide](https://secure.php.net/manual/en/migration70.incompatible.php). Naming a class `Error` without being in a namespace is going to cause your code severe pain going forward.

The reason this class is defined in random_compat: random_compat is a PHP 7 polyfill and thus aims for API compatibility. This means instead of shoehorning everything into an `Exception`, it defines `Error` and `TypeError` as separate error conditions.

Recommended solution: Rename your internal Error class, at the very least to use namespaces. This will save you a lot of pain when PHP 5.6 is expired and you're trying to update to PHP 7.

**Comment by defuse** [comment]
Thanks @paragonie-scott!

**Comment by mi6crazyheart** [comment]
Got it. I really didn't know about this. Thank for the information.
