### ISSUE TITLE
Support: How can I create a valid ciphertext using openssl command line?

### ISSUE THREAD

**Issue by airways** [defuse/php-encryption#282]
This is what I'm doing now to encrypt a block of JSON data to be passed to an API that will eventually be decrypted by Crypto::decrypt:

    export site_secret=def00000dc8b230b40c4b36bb5aaba92b46f78b329e4a990675b809f0abd5cd3d091392fa48b002445a8ab1639a2e20ca18a2a5722210cad81454810c5c4e684bea885cc
    echo '{
        "events": [{
            "timestamp": 1468967143,
            "ip": "127.0.0.1",
            "variable": "id",
            "value":"test"
        }]
    }' \
    | openssl enc -e -aes-256-ctr -nopad -nosalt -k $site_secret | od -A n -t x1 | perl -pe 's/\s+//g'

(This is currently run on mac os but should work anywhere really.)

This _almost_ seems to work (it produces a reasonable looking encrypted string) but is currently generating 'Bad version header.' error when I try to decrypt with:

    $key = CryptoKey::loadFromAsciiSafeString('def00000dc8b230b40c4b36bb5aaba92b46f78b329e4a990675b809f0abd5cd3d091392fa48b002445a8ab1639a2e20ca18a2a5722210cad81454810c5c4e684bea885cc');
    return Crypto::decrypt( '8469daf9b92f9b5126ff67061b9d2937b3069c8c0598cea857279fa3e93bfdc7dc2b84b8b50fc0e1c2e6daddbf1fc7199fe777e57946c82649a9ccfab4c10d81d9fc05699e2dce929c3962ae6613e8bb2f1abaec712e657c55a69da9e8e48d07d1d912e5879f52110001888b0bd9516ee07a11ffe9338818ede22074771b13009c8b0971c2c270b42dae13dc87f585b3c2f17a9338752a047335617bb7df563b357ac6a491', $key);

It looks as if the Crypto::internalDecrypt() only expects to receive a ciphertext from it's own Crypto::encryptInternal implementation.

Two things:

1) Academic: Is this not technically a weakness as it prevent testing via interop with other encryption libraries?

2) Practical: How **should** I generate the correct string?

**Comment by paragonie-scott** [comment]
> 1) Academic: Is this not technically a weakness as it prevent testing via interop with other encryption libraries?

The only thing preventing testing is [not reproducing the exact message format](https://github.com/defuse/php-encryption/blob/master/docs/CryptoDetails.md).

This is what each message consists of:

* A four byte header, two of which contain version information
* A 16-byte random nonce for CTR mode
* A 32-byte random salt for HKDF
* The ciphertext
* The HMAC-SHA256 of all of the above

Each of these things is important for security.

* The version information in the header is useful for if a BC break is needed, the library knows what rules to apply (and/or to reject the message in the main `decrypt()` method).
* The nonce for CTR mode makes ciphertexts indistinguishable from one another, even if the same plaintext is used repeatedly.
* The HKDF salt has a lot of interesting properties. In particular, the actual key used for encryption is different for each message (but is derived from the master key you provide the `encrypt()` and `decrypt()` methods). As a consequence, although a 128-bit nonce has a 50% chance of experiencing a single collision after 2^64 messages, the birthday bound of the salt colliding is 2^128 messages. In order to experience a nonce reuse condition, you'd need both to happen, which is expected to happen with 50% probability after 2^192 messages.
* The MAC prevents chosen-ciphertext attacks.
