### ISSUE TITLE
Provide a PHP native stream wrapper.

### ISSUE THREAD

**Issue by dawehner** [defuse/php-encryption#283]
Background: I try to integrate the defuse php-encrpytion library into a file system agnostic piece of code, so that defuse is just one of the potential libraries to be used for encryption.

In order to scale those operations up we need a way to not store the entire file in memory, but rather provide some form of streaming interface.

One idea I had was to write an integration into [Flysystem](http://flysystem.thephpleague.com/).
While writing files was rather easy: https://github.com/dawehner/defuse-flysystem/blob/master/src/FlysystemAdapter.php#L53 reading a file wasn't actually possible in a streaming way.

The general problem: Defuse just provides a way to encrypt/decrypt an entire stream. In an ideal world, we would have a StreamWrapper implementation. Do you think this would be even remotely feasible?

**Comment by paragonie-scott** [comment]
A stream wrapper implementation implies "random access file encryption/decryption" which is great if you aren't worried about chosen-ciphertext attacks. I'm not aware of any techniques for offering that flexibility (in reasonably a performant manner) while still being authenticated encryption, especially from PHP.

If anyone knows any papers on this subject, I'd be greatly interested in reading them.

**Comment by twistor** [comment]
@dawehner I attempted this as well https://github.com/twistor/flysystem-encrypt

@paragonie-scott It's possible to make a stream wrapper implementation non-seekable.

Even better than a stream wrapper, would be a stream filter: http://php.net/manual/en/filters.encryption.php

**Comment by paragonie-scott** [comment]
> Even better than a stream wrapper, would be a stream filter: http://php.net/manual/en/filters.encryption.php

Yes, that's something I believe everyone would find useful. :)

**Comment by twistor** [comment]
@paragonie-scott The write case isn't too complicated. As far as stream filters go.

@dawehner and I have been discussing this issue.
Would a decryption stream filter that throws an exception if the HMAC fails be sufficient?

**Comment by defuse** [comment]
The difference between what's proposed and what's currently in the code is that the current code can only read/encrypt the entire contents of a stream and encrypt the entire contents, and what's proposed is to allow the user to do write operations into a stream to encrypt and read operations into a stream to decrypt?

**Comment by twistor** [comment]
Yes, that's pretty much it. To rephrase: encrypt/decrypt without having to make a full copy in memory.

**Comment by geek-merlin** [comment]
I'm also interested in this and may work on it.

(Fun to come to the party and see most of "the usual suspects" - we really should ping @colans ;-)

**Comment by cbj4074** [comment]
I, too, am interested in this, specifically so I can output from a stream, e.g., to a user-agent in the form of a download, without having to either:

1. Read the entire file into memory
2. Write plaintext data to disk

In the interest of scaling well, the memory consumption cannot be a function of the input/output file size.

I also need to be able to:

1. Encrypt from `php://input` stream without writing plaintext data to disk (it sounds as though this may already be possible via Halite)
2. Re-encrypt a file, with a new key, "in place", with streaming (i.e., not reading entire file into memory), atomicity, without writing plaintext to disk in the process

I happen to be using Flysystem, too, although I welcome a more generic implementation, of course.

Has the status of this issue changed recently, and/or is some/all of this possible already with Halite?

Thanks for this wonderful library!

**Comment by defuse** [comment]
I do not have time to commit to this so I am going to close this issue, but thank you for the great suggestion!

**Comment by colans** [comment]
Why not leave it open for others to work on via merge requests?

**Comment by defuse** [comment]
Because I don't even have time to review merge requests. To be 100% honest I'm becoming an alcoholic, depressed, low self-esteem, and I just can't do this anymore. My eyelid is infected and has been since January (3.5 months ago) and I'm too stressed out to even see a doctor about it, my taxes are almost overdue because it's gonna take me a few days just to gather the material to send the accountant who doesn't know what the fuck they're doing and so I'm under constant stress of being audited and finding out I'll get a huge fine or even jail time. I bought a bunch of shit to try to make myself happy and half of that ended up broken and needs to be returned and I'm procrastinating doing that because of the stress so I'm just going to lose the money. My landlord might want to kick me out at the end of the lease this month, I can't buy a house because the bank won't accept my money because I work in cryptocurrency. My girlfriend is on tinder looking for other partners even though I don't want a poly relationship. The leadership at work is causing a whole bunch of negativity that I have to deal with and I can't focus on doing my job of preventing us deploying vulnerable code. My dad's heart condition means he has limited life left. I lost my best friend because he got involved with a cryptocurrency scam with John McAfee. My driver's license has been expired for 2 months now. I'm about to lose another best friend because I don't have the energy to help with his OCD. So, sorry, I can't contribute to this library anymore for the time being. Unless there's some kind of critical vulnerability please just assume I don't exist.

**Comment by Slamdunk** [comment]
To anyone still interested in the topic, I've used `libsodium` `XChaCha20-Poly1305` encrypted stream to create a PHP native stream wrapper; it extends the native [`php_user_filter`](https://www.php.net/manual/en/class.php-user-filter.php) instead of `StreamWrapper`, but it accomplish the same goal.
https://github.com/Slamdunk/flysystem-compress-and-encrypt-proxy/blob/v0.1.0/src/EncryptorStreamFilter.php
Feedbacks are welcome :+1:
