### ISSUE TITLE
Why distinguish between CannotPerformOperationException and CryptoTestFailedException?

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#29]
From the user's perspective, both of these are the same: Something is *seriously* wrong and a human needs to take a careful look at what's happening. Why are they different exceptions? In what case would the user benefit from being able to distinguish the two?

**Comment by sarciszewski** [comment]
A test failing means that something is wrong with the runtime tests (e.g. there's something wrong with how PHP/openssl calculated the test vectors).

If the crypto operation cannot be performed, this is because they do not run a supported version of PHP.

I do think this difference is worth highlighting. The former is "it could be PHP, or it could be the Crypto.php" the latter is "it's not installed correctly". Troubleshooting time greatly decreases this way.

**Comment by defuse** [comment]
Good points, I'll leave it as-is.
