### ISSUE TITLE
Hash of a Key

### ISSUE THREAD

**Issue by Schnoffel** [defuse/php-encryption#291]
Another more common question:

Is it a security issue when I create a hash of an in raw bytes saved or by saveToAsciiSafeString() retrieved key? Would this decrease the security or is it irrelevant?

I would do this for checking purposes, so I can prevent users to store an invalid key without the need to try to decrypt a file (when there is already a encrypted file) and to prevent a user uses a wrong (but valid) key for encrypting new data.

**Comment by paragonie-scott** [comment]
If you're storing `H(K)` with your message, and `H()` is a weak hash function, that may give attackers information about `K`.

If you were going to go this route:

1. Make sure `H()` is a strong hash function, like BLAKE2b, Keccak, SHA-512/256, or SHA-384
2. Consider a blind index, based on HMAC instead of a raw hash, with a key unknown to the machines that know the ciphertext but not the key to decrypt it.

An even better idea, however, would be to assign a randomly generated UUID to the key and only store the UUID with the message rather than anything related to (or, especially, derived from) the key.

**Comment by Schnoffel** [comment]
Thanks for your answer. Currently I'm using SHA-512 for hashing and checking the key.

But just out of academic interest, could you go more into detail when you say a weak hash function could give attackers information about `K`? Let's say that `K` is a randomly generated key (/dev/urandom) and we use MD5 for hashing. Even if we could find a collision, is it wrong when I say it would be extremely unlikely that we find the correct `K`?

**Comment by paragonie-scott** [comment]
Generally, if I find an input that produces that MD5 hash output, the chance that it's actually a collision and not the original input is very small for human generated inputs. I don't think this would hold true for a randomly generated key.

But then again, who's to say that cryptographers wouldn't discover an attack against such a protocol that uses multiple 2-block collisions (which each carry a cost of about 2^20 if I remember my literature correctly) that leaks some bits of the original 256-bit key and helps to optimize future brute force attempts on the original key?

Using a UUID as a key identifier sidesteps this entirely. Using HMAC-SHA384(known_key, some_unknown_key) would increase the cryptanalysis difficulty from O(n^k) to O(n^(k+1)).

**Comment by Schnoffel** [comment]
You are right. So I think best solution here is to use a UUID which is directly appended to the beginning/end of the key.

**Comment by defuse** [comment]
Storing H(K) is risky because of protocol interaction vulnerabilities (a.k.a. chosen protocol attacks). For example, `defuse/php-encryption` might internally use H(K) for some other purpose, assuming it will be secret. But then in your application H(K) is public, so security breaks. `defuse/php-encryption` currently doesn't do this, but I haven't *documented* that it doesn't, so it might in the future.

UUID is the way to go. Thanks @paragonie-scott for suggesting that!

**Comment by Schnoffel** [comment]
Today I made an update so an UUID is used for checking; so the key now is stored as string(UUID . KEY) and the hashed were fully removed.

But I thought about another possibility: What about decrypting a test file? Is that also a proper solution for checking if the encryption key is correct?
