### ISSUE TITLE
stream_set_read_buffer()  error

### ISSUE THREAD

**Issue by cssimmon** [defuse/php-encryption#294]
Would love to use this library but seeing undefined function error on hosted site.  On my development environment this works just fine. Any ideas what I might cause this?  I am attempting to do full file encryption on large files but this error happens on any size file.

\nFatal error: Call to undefined function stream_set_read_buffer() in defuse-crypto.phar/src/File.php on line 194

Thanks

**Comment by paragonie-scott** [comment]
https://secure.php.net/manual/en/function.stream-set-read-buffer.php

What version of PHP are you running? This function should be in 5.4.0 (the minimum supported PHP version, although we should consider raising that to 5.6 if we do another release).

**Comment by cssimmon** [comment]
Thanks for responding so quickly. I looked at the php docs for that method and im running 5.6.  Here is the relevant system info.

-Server Info--
PHP Version:5.6.99-hhvm
Webserver Info:Apache

--PHP Info--
PHP Info:5.6.99-hhvm
Operating System:Linux 
PHP Safe Mode: Off
Memory Limit:17179869184
Curl Installed:True

**Comment by paragonie-scott** [comment]
`5.6.99-hhvm` Interesting. I'm not sure how HHVM works here. Let me see if I can ask someone who might.

**Comment by paragonie-scott** [comment]
(Let's see what #295 turns up.)

**Comment by cssimmon** [comment]
Thanks Scott, appreciate you being so responsive.

**Comment by sgolemon** [comment]
Looks like HHVM only added stream_set_read_buffer() on May 17th of this year.
https://github.com/facebook/hhvm/commit/8cf8bb6a5c299e701141804c5dd809d41e232a58#diff-3e048eb7f3093027eac6d69527d925e7

Not clear what version of HHVM is running on your server, but if it's advertizing 5.6.99, then it's probably older than a year (I think, I can't recall the exact mappings).

Out of curiosity, I'd ask for the output of `<?php var_dump(HHVM_VERSION);`, but ultimately the fix for this library will need to be a function_exists() check and some kind of BC handling (or set a higher minimum hhvm requirement).

**Comment by sgolemon** [comment]
Oooh, and it looks like the implementation is incomplete too.  It'll only work on plain files (which might be enough for defuse/php-encryption, I haven't looked at the library).  Should prolly file a bug against HHVM to make it support network streams as well though.

**Comment by cssimmon** [comment]
Thanks Sara,
Looks like HHVM_VERSION = 3.9.1.   Looks like there is an pull request from Scott to add a check for that stream buffer.

**Comment by paragonie-scott** [comment]
The undefined function on HHVM should no longer be a source of irritation in 2.0,2+.
