### ISSUE TITLE
Why is it so slow?

### ISSUE THREAD

**Issue by ntoniazzi** [defuse/php-encryption#318]
Hello,
I'm trying to replace mcrypt with php-encryption in my encryption process, but I'm facing a problem: every encryption/decryption takes about 300ms to complete, event with a simple word. Is it normal? Is there a way to optimize it? In my web context, it's not acceptable.
Thanks.

php 5.6.30

```php
include "vendor/autoload.php";
for ($i = 0; $i < 4; $i++) {
  $s = microtime(true);
  Defuse\Crypto\Crypto::encryptWithPassword($i, "key");
  printf("%d: %3dms\n", $i,(microtime(true) - $s) * 1000);
}
```
Result:
```
0: 317ms
1: 314ms
2: 314ms
3: 314ms
```

**Comment by defuse** [comment]
Yes, it's normal. The only way *password-based* encryption can be safe is if you first generate a key from the password by applying a slow "key stretching" function. What this library does, if you use `encryptWithPassword` or `decryptWithPassword`, is it first runs the password through an intentionally-slow key stretcher to make it safe for use with passwords.

To speed up your application, you can do one of two things. If the key is just stored somewhere on the server, just use a completely random key instead (you can get one by calling `Key::createNewRandomKey()`) and then encoding/decoding it to strings with  `saveToAsciiSafeString()` and `Key::loadFromAsciiSafeString()`. The other option, if the encryption is really being done with passwords and you can't store a completely random key, then use `KeyProtectedByPassword` so that once you get the password, you only have to decrypt the key once (this will be slow as `decryptWithPassword` is), then you can use the key for all of your data encryption and decryption, which will be fast.

**Comment by ntoniazzi** [comment]
With the random key stored on the server and loaded on-demand, the encryption/decryption has been stripped down to under 8ms.
Thanks.
