### ISSUE TITLE
Why isn't PHPUnit in composer.json?

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#322]
See this comment here: https://github.com/defuse/php-encryption/pull/320#issuecomment-277647893

We do our own signature checking for PHPUnit, so it's probably for security reasons. But the [release instructions](https://github.com/defuse/php-encryption/blob/master/docs/InternalDeveloperDocs.md) use composer so composer-sourced code is getting run anyway.

Figure out if there's any good reason not to get PHPUnit via composer.

**Comment by paragonie-scott** [comment]
> Figure out if there's any good reason not to get PHPUnit via composer.

There isn't anymore. Composer used to have weak HTTPS enforcement, but that's now fixed.

There is a possible concern that the phpunit that gets installed isn't authentic (and thus, security concerns), but it's going to most likely get loaded from cache anyway, since most projects ship with phpunit.

I'd suggest:

1. Keep the phpunit.sh script on-hand for people whose threat models include compromised infrastructure for phpunit's website (but not Sebastian Bergmann being compromised).
2. Add it to composer.json's require-dev for ease-of-use by others.
3. Just get Travis to use the Composer-provided phpunit.

**Comment by defuse** [comment]
I think this is done (looks like it's in composer.json now) so I'm closing this.
