### ISSUE TITLE
hash_equals arguments inverted?

### ISSUE THREAD

**Issue by HeineDeelstra** [defuse/php-encryption#328]
The documentation on PHP's hash_equals states that "It is important to provide the user-supplied string as the second parameter, rather than the first.".

verifyHMAC however provides the user-supplied string "$correct_hmac" as the first.

This was noted in https://github.com/defuse/php-encryption/pull/30 , but I could not find further discussion.

**Comment by defuse** [comment]
Good catch, the bug is in this line here: https://github.com/defuse/php-encryption/blob/master/src/Crypto.php#L370 Also the terminology "correct HMAC" should be fixed there, since neither the computed one nor the one that's in the ciphertext should be considered "correct" (they can both be wrong).

**Comment by larowlan** [comment]
working on PR

**Comment by defuse** [comment]
Thanks!

**Comment by defuse** [comment]
Leaving this open to investigate the actual security consequences and see if it's important to put out a new release etc.

**Comment by paragonie-scott** [comment]
[PHP source code for `hash_equals()`](https://github.com/php/php-src/blob/b7f59be9f48d0079e222e26c01cd0a067480b97e/ext/hash/hash.c#L826-L865).

> `for (j = 0; j < Z_STRLEN_P(known_zval); j++) {`

This looks dangerous, but right above it

>     if (Z_STRLEN_P(known_zval) != Z_STRLEN_P(user_zval)) {
>         RETURN_FALSE;
>     }

There's no avenue for exploiting the loop's dependence on the length of the "known" string, because if it doesn't match, it fails early. Using them in the wrong order has no security implications, but is still worth doing *correctly*.

**Comment by defuse** [comment]
I think the "It is important to provide the user-supplied string as the second parameter, rather than the first." part of the PHP manual is wrong. If the lengths are the same, it's not important since the code is symmetric. If the lengths are different it's not important either because the manual says, separately, "When arguments of differing length are supplied, FALSE is returned immediately and the length of the known string may be leaked in case of a timing attack."

So I don't understand why the manual is even saying that, other than just to make sure your code is consistent with its parameter names.
