### ISSUE TITLE
Fatal error: Uncaught exception 'Defuse\Crypto\Exception\WrongKeyOrModifiedCiphertextException' with message 'Ciphertext is too short.' 

### ISSUE THREAD

**Issue by iyasilias** [defuse/php-encryption#349]
I get this error when trying to decrypt a text:

`Fatal error: Uncaught exception 'Defuse\Crypto\Exception\WrongKeyOrModifiedCiphertextException' with message 'Ciphertext is too short.' `

But when I decrypt with simple test file, the encrypted text successfully decrypted.

**Comment by paragonie-scott** [comment]
Are you passing the filename instead of the file contents?

**Comment by iyasilias** [comment]
Sorry my bad. It is actually an error somewhere else (mysql result is null).
Maybe instead of 'Ciphertext is too short', you could  differentiate a message for **null** string.

**Comment by paragonie-scott** [comment]
I created a pull request that throws a `TypeError` (polyfilled by random_compat on PHP < 7) if you pass anything other than a string.

Does your code pass `"NULL"` as a string? If so, that's an oddly specific use case that we can't afford to handle for everyone, because it adds needless complexity and risk for side-channels. If it's `null` (as in an empty value), then #350 will address this sort of confusion.

**Comment by iyasilias** [comment]
Just for record, it turns out the query result is _NULL._
