### ISSUE TITLE
Which AES Key Size?

### ISSUE THREAD

**Issue by sarciszewski** [defuse/php-encryption#35]
References: 
 * http://eprint.iacr.org/2009/317
 * http://eprint.iacr.org/2009/374

Attack complexity based on the two papers:

* AES-128 = 126.1 bits
* AES-192 = 172 bits
* AES-256 = 99.5 bits

Given this, I feel that AES-192 is the safest of the three choices.

If everyone agrees, we need to get new test vectors written in the runtime tests then change the key size from 16 to 24.

**Comment by defuse** [comment]
Here's the attack on AES-128:

http://research.microsoft.com/en-us/projects/cryptanalysis/aesbc.pdf

**Comment by defuse** [comment]
Even though 172 > 126.1, the difference between 192 and 172 is a lot greater than the difference between 128 and 126.1. That tells me (admittedly, without actually understanding the attacks), that AES-128 is still more resillient to cryptanalysis. Bruce Schnier also recommends AES-128 for new applications (https://www.schneier.com/blog/archives/2009/07/another_new_aes.html).

I think for simplicity we should stick to AES-128. Thoughts?

**Comment by timoh6** [comment]
> I think for simplicity we should stick to AES-128. Thoughts?

I'd prefer 256-bit version because the longer key has a better safety margin against (practical) side-channel leaks.

Given that side-channel leaks are a real problem, I think it is better to offer more security margin against them, than offer more security margin agains (only theoretical) related-key attacks.

Thoughts?

**Comment by sarciszewski** [comment]
Correct me if I'm wrong, but doesn't openssl use AES-NI for fast, cache-timing-safe crypto? What other side-channels do we have to consider?

**Comment by timoh6** [comment]
Right, the most obvious way to deal with the cache timing attacks is (according to the current understanding) the use of AES-NI. But this has some requirements, software and hardware support, and that's why I wouldn't dare to count blindly on it (although possibly a good share of running PHP code has the underlying required processor and recent enough OpenSSL).

But if you compare that with the related key attacks, which are not practical, I think it is better tradeoff to "suffer" from those attacks, than it is to "suffer" from timing side-channels.

I'd dare to say it is a lot bigger attack surface to exploit some side-channel to break the encryption, than it is to exploit some AES related attack (like those related-key attacks) to break the encryption.

**Comment by sarciszewski** [comment]
I'm inclined to agree, but I'm going to hold off on any PRs until I've heard from more people. Thanks. :)

**Comment by sarciszewski** [comment]
Solar Designer says AES-128.

**Comment by CodesInChaos** [comment]
Related key attacks are irrelevant if you use a proper random key. If you don't use a proper key, fix your protocol.

I'd consider AES-128 strong enough, but I have little doubt that properly used AES-256 is stronger. Not only is the key larger, but the additional rounds increase resistance to cryptoanalysis. The biggest downside of AES-256 is that the CPU cost increases by roughly 1.4 times, but that only matters if you encrypt a lot of data.

**Comment by CodesInChaos** [comment]
@sarciszewski
My reading  of solar designer's comment is that he recommends AES-128 if you derive the key using PBKDF2-HMAC-SHA1 since its native output size is smaller than the key size of AES-192. If you derive the key differently, this concern shouldn't apply.

**Comment by sarciszewski** [comment]
@CodesInChaos 
Okay, thanks for the clarification. So if you had to recommend one keysize for AES, what would it be?

**Comment by sarciszewski** [comment]
I think we can close this for now and revisit later. The current key size is clearly strong enough.

**Comment by spaze** [comment]
Just for the record, Thomas H. Ptacek says 

> Go ahead and use 256 bit keys.

And

> Avoid: constructions with huge keys, cipher "cascades", key sizes under 128 bits.

Source [this gist](https://gist.github.com/tqbf/be58d2d39690c3b366ad) linked from [this tweet](https://twitter.com/tqbf/status/602159784624726016).

**Comment by paragonie-scott** [comment]
Hi @spaze, I don't think @tqbf was being *inclusive* when he said "key sizes under 128 bits".

**Comment by tqbf** [comment]
I don't have the context for this discussion but will wrap up my (mercifully for all of us brief) involvement by saying I do not have any opinion whatsoever on whether you should use AES-128 or AES-256. I don't even know what system we're talking about and I still feel comfortable asserting that the 128/256 issue is not ever going to be what gets this system compromised.

**Comment by spaze** [comment]
Hi @paragonie-scott, agree, I've posted it for the record, so that more opinions (in addition to Solar Designer's one) are in one place. Didn't mean to express anyone's position on keysizes in any way.
