### ISSUE TITLE
Partially decryption

### ISSUE THREAD

**Issue by Schnoffel** [defuse/php-encryption#351]
Is it possible to partially decrypt big files?

**Comment by paragonie-scott** [comment]
Sure, it's possible. We are using CTR mode, after all.

It's not an out-of-the-box feature, however.

**Comment by Schnoffel** [comment]
Thanks for fast answer Scrott. Do you perhaps have an example?

**Comment by paragonie-scott** [comment]
You'd essentially need to take something like `decryptResourceInternal()` [here](https://github.com/defuse/php-encryption/blob/5176f5abb38d3ea8a6e3ac6cd3bbb54d8185a689/src/File.php#L433-L683) and allow arbitrary start/end points for the actual decryption. I'd definitely suggest **not** skipping the HMAC verification part of it.

**Comment by Schnoffel** [comment]
Okay, then I will try do do this. I am not a professional but I will try do change very less of the `decryptResourceInternal()`.

Thanks for providing such a framework!

**Comment by paragonie-scott** [comment]
I don't know if @defuse will want to make this a normal feature in a future release, but if so, this is a good ticket for tracking it.

**Comment by Schnoffel** [comment]
It would be very nice and elegant as there are cases were it does not make sense to decrypt the whole file. 

Currently I try to change the `decryptResourceInternal()` so I can read from X to Y bytes. I think it can only be a multiple of `Core::BUFFER_BYTE_SIZE`. Should I check the HMAC for the whole file or only for the part I want to read?

**Comment by paragonie-scott** [comment]
You're going to have to do a full pass to verify the HMAC, since a partial HMAC doesn't exist.

**Comment by defuse** [comment]
What's your use case for partially decrypting a file? Unless you're having performance problems as a result of decrypting the entire file and then reading the part you want out of the plaintext, I would avoid this.

**Comment by Schnoffel** [comment]
It's an performance issue because I have big files (up to 15 GiB) where I only need 20 MiB for example. Currently I have to decrypt them as a whole and cache them which needs much CPU and time and is not a good solution. Also it decreased the security because when I can decrypt just parts I can do this directly in the memory without creating any temporarily decrypted files at all.

When I do a full HMAC as expected I have the problem later when I just decrypt parts of the chiphertext:

`File was modified after MAC verification`

**Comment by defuse** [comment]
I wonder if you'll still run into performance problems with partial decryption because the HMAC check will have to read in the entire file. You might need some cryptography that's more custom-designed to your specific use case here.

The code was designed to refuse to give up any plaintext until the HMAC has been checked, so I'm not surprised you're running into problems. What are the security properties of the location you're storing the ciphertexts? If it's assumed an attacker can modify the files there, then a separate whole-pass HMAC check won't be secure because the attacker can quickly modify the file in the time *between* when it is read for the HMAC check and when it is read again to get the part you want to decrypt. The way to avoid that would be to save the desired part of the ciphertext during the HMAC pass, so that you're sure what you're decrypting is the same as what passed the HMAC check.

Maybe with some more information about your application (what it is, why the files are encrypted, where's the key stored in relation to the files, what the security requirements are, etc.) I can see if there's a more off-the-shelf solution to the problem.

**Comment by Schnoffel** [comment]
Thank you very much for your answer. You are right: I run into performance problems because the HMAC check will read the whole file. I checked the time one hour ago and for 10 GiB it takes (too) long time.

It is a private media library. There I store my private documents as .pdf files or photos but videos also. As security is very important for me I want all files to be encrypted. With the documents there is no problem at all because they do not exceed 1 MiB per file averaged. Same goes for the photos. But with the video files I run into troubles: I can decrypt them and send the decrypted chiphertext to `php://output`. When doing this there is no performance issue because modern browsers are able to stream prepared .mpf files. But this a twist: I cannot continue the video when Internet connection fails or something like that, so I have to play the video from the beginning. The reason is the file has to be fully available on the disk (not on the clients computer), but it isn't when being decrypted. So I have to decrypt the whole file, and save it temporarily on the disk. Then this works because modern browsers can send byte start/end markers to the http server.

I hope you understand what I mean :) Currently I decided to fully decrypt the file to the disk and remove it automatically then when work is done. But that is not the best solution I think.

**Comment by defuse** [comment]
That makes sense. Yeah, that's not ideal because it will leave traces of plaintext on the server's drive. You could do the decryption to a filesystem that's encrypted with full-disk encryption, with a random key generated at boot time. That way at least when you power the server off or reboot it there won't be any traces of plaintext left on the disk. Still not ideal.

If you don't think anyone would be able to maliciously change the files, then skipping the HMAC check for big files might be fine. (Beware: even if you don't care about the files themselves being changed, sometimes there are ways to change files in ways that make it easier to find out what their contents are, e.g. changing the "To:" address in a draft email).

Otherwise yeah, you would need some custom crypto that does something like:

1. Store a MAC for each "chunk" of the file. This is imperfect: An attacker could remember past versions of the file and swap specific chunks for older verisions of the same chunk, or
2. Use some kind of keyed Merkle tree structure over the file's contents so that with by reading only O(log(n)) more data you can authenticate the entire file.

(Thinking out loud...)

There are lots of potential problems to consider at the higher application layer, like if an application starts streaming a file today, stops halfway through, and then wants to continue 3 days later after the file has changed, should it be allowed to? I can imagine applications where small issues like that would bubble up into bigger security problems.

So I think solving the partial decryption problem should be out of scope of this library. It's an interesting problem so maybe we can revisit it once we have more resources.

**Comment by Schnoffel** [comment]
Thank you for your competent answer!

If someone would change the files it would be not a generally problem, but I don't know if someone could be able to use some browser/player exploits then. But if someone could change files he could change other files maybe too. The be frankly I do not know if it would be a security concern because in contrast to the document files the video files don't have to be 100 percent trusty as they do not contain information which could be harmful when wrong.

For now I decided to fully decrypt the files and remove them when finished. Not perfect, but maybe it is better to wait some time before creating a very complex, maybe harmful solution myself.

Again thanks for your answers, you are doing real good work!

**Comment by Kaulkwappe** [comment]
Would be still very nice if partially decryption would be possible.
