### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by dpantel** [defuse/php-encryption#355]
Is this a really stupid idea?

I have some data that I need to store in a DB, but this data should only be accessible to authorized users (for compliance).  Since I don't necessarily trust my DB host, the obvious solution is encrypt the data using a library such as this one.

The problem is that both the application and DB are on the same host (and a shared one at that), so a malicious root user only needs to go the small extra step of saving the key stored by the application to get clear-text data out of the DB dump.

So, here is my proposed solution to that:
1. generate a key and encrypt all the sensitive data
2. generate a key-with-pass for each individual user, using their login password and store these keys in the DB
3. encrypt the data key (from step 1) with the individual user keys (from step 2) and store the ciphers in the DB along with the user keys

Obviously, this completely obliterates the separation between the data storage and the key storage (all in DB), however much security that offers in my case.  The other concern is that I don't necessarily trust that the users' passwords are "strong" (out of my control at the moment).  And finally, I don't have a great solution for managing an unlocked user key.  The obvious thought is to stick it in $_SESSION, but I am not sure how secure that is.

What do you guys think?  Is this dumb?

**Comment by defuse** [comment]
This would have low security/cost benefit because a compromise of any one of the user's passwords will make it possible to decrypt the data key and thus decrypt the database (all an attacker has to do is create an account on the server and the data key will be encrypted with a password of their choice). When everything is stored on one server that's online 24x7, cryptography isn't all that useful. Whatever can be done on the server normally (such as access to data) can be done by an adversary who has compromised the server. No amount of cryptography will change that.

So this is an appsec/devops engineering question: How do you design your system's architecture so that data is safe even when components that are likely to fail, fail? I'm not an expert in this (and I don't know what kind of system your building) so I can't offer great advice, but the usual principles are to avoid collecting sensitive data in the first place, keep the system simple, isolate parts that don't ever need to talk to each other, only give components the minimal amount of privilege they need to operate, move data that's no longer needed offline, put methods in place to detect successful attacks, and keep tamperproof incremental backups so restoring from any "hack" is a quick and reliable procedure.

**Comment by flowdx** [comment]
In general, your thoughts are right i guess. You've evolved a solution/concept for data-encryption in a multi-user-environment. Many people did this before you and were facing the same problems, like the need for strong user-passwords (perhaps you can support/force them to make use of strong passwords) and difficulties with resetting passwords or how to deal with users that are leaving the environment. But in general, you concept should work like this. 

The following is important: Your solution, or any other implementation with this library on a system that isn't physically under your control, will not solve the problem, that you can't trust your host. If you use this library on a webspace of an external hoster, the encryption and decryption is done on that server and so the keys and/or the decrypted data will be present in the memory of that server. There is no secure solution for that problem if the encryption and decryption isn't done clientside. If you can't trust (and perhaps you shouldn't trust) the server-administration, storing data like this isn't VERY secure. But perhaps it's at least secure enough, cause, if the library is correctly implemented, it can at least secure the data you store in the db for the case that your database will be read out on a 'side-channel' without compromisation of a user-account. 

Storing an unlocked userkey in a session is a practicable solution cause if your program or hoster has no security issue that would allow a third person to extract that key from the session, it can't be acessed and the key exists only in the server-side session-memory. This leads back to the described above: it is readable for someone, who has control of the server and its memory itself.

**Comment by dpantel** [comment]
Of course you are both right in that the system is not very secure by default.  Unfortunately many aspects of the setup are out of my control, and I am simply trying to crowbar and bandaid a "solution".  Thank you for your thoughts.
