### ISSUE TITLE
Private messages encryption

### ISSUE THREAD

**Issue by Schnoffel** [defuse/php-encryption#356]
I thought about using Defuse for private messages encryption on a platform (like a forum).

Goal is to prevent people who have access to the database from reading private messages. It should be automatically done with no extra effort for the user, I call this 'invisible encryption'. Not possible with this approach is to beat off attackers from the network/servers because the message text is still sent from the users browser to the website in plaintext, even if over TLS. So if the server would be hacked the attacker could read all new private messages and also could trap the passwords from users logged in after the attack and then also read old encrypted messages. To prevent this an end-to-end encryption would be needed, but that is too complicated I think and would decrease the users comfort which is important here.

So the main goal here is to prevent having a database with private messages in plaintext.

As this communication is asynchronous done I don't think Defuse is the proper tool for this. Can you recommend or do you have a framework for asymmetric encryption?

Thank you very much!

**Comment by defuse** [comment]
If code running on the server will have access to the messages (which it has to since the encryption isn't happening in the client), then an attacker who breaks into the server will be able to access the messages too, using the same mechanism the legit code does, no matter if they're encrypted. As far as I can see your only options are either to (A) take responsibility for protecting the message data against attackers by having really good server security or (B) implementing end-to-end encryption of the messages.

**Comment by defuse** [comment]
Oh, I this is for a web forum. In a web app, you can't implement end-to-end encryption because the crypto code has to be sent from your web server (which might be hacked) anyway. You could *try* to do something like derive public/private key pair from the user's password and encrypt messages between users that way, but then if an attacker broke into the server they could install a backdoor that captures the private keys as soon as they're decrypted and the crypto would be worthless.

I think the best you can do in this setting is to design your system's architecture so that it's really really hard to hack the database, which is not something I'm an expert in.

**Comment by Schnoffel** [comment]
Thank you very much for your answer!

Aside from backdoors which would need more complex knowledge than just reading the private messages in cleartext a reason is also it should not be possible for the webmaster to read private messages. As I am the webmaster I know I would not do this, but I don't like it having private messages fully unprotected as they often contain personal information, so I want to ensure a minimum of security. Same goes with passwords: Even if the main reason wouldn't be a hacker could steal it it would not be nice to save passwords in clear text.

So I am looking for methods to increase the users security without adding to much complexity. 

I think the public/private key pair would be a proper way! Maybe defuse for data only the user can read and is not shared to other users like private messages or chat messages.
