### ISSUE TITLE
I need help for decryption using another programming language

### ISSUE THREAD

**Issue by Lomse** [defuse/php-encryption#365]
First off, great library. So simple to implement!

I have a frontend app written in PHP which does the encryption and save it into the db. At the backend, there is a service written in NodeJS which is supposed to get the encrypted string from the db and **decrypt it**. I have read the **Cryptography Details** in the **doc** but I'm not sure about how to implement the decryption of the encrypted string using another language. 

Any explanation is highly appreciated. Thanks
/Selom

**Comment by defuse** [comment]
It's nontrivial to do this because you're essentially re-implementing the library in a different language, and there are security pitfalls that need to be avoided in order to do that (it's a lot of work). I'd first recommend trying to get both sides using libsodium...

- https://github.com/jedisct1/libsodium-php
- https://www.npmjs.com/package/libsodium

...instead of this library, since it has compatible implementations in many languages.

**Comment by sergio91pt** [comment]
If the project is already in production, changing to another (non-compatible) encryption library may also not be trivial...

About a month ago, I ported v1 of this library to NodeJS. It is not that hard (for v1 atleast, since it is a single file), the only tricky part is HDKF, where you should check the RFC and understand how it works, instead of just "blindly" porting the code. All you need is [Crypto](https://nodejs.org/docs/latest-v6.x/api/crypto.html), [Buffer](https://nodejs.org/docs/latest-v6.x/api/buffer.html) and unit tests.

@Lomse If you still need it, I can talk to my employer about making the code public.
