### ISSUE TITLE
Support API for Encrypting/Decrypting files.

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#39]
You can't encrypt super-large files with this library because you have to load them into RAM. We could either (1) Have a "stream" sort of API, where you feed it data and it feeds back ciphertext, but there are problems with this, e.g. when decrypting you'll get all of the plaintext and then only the last call will check the MAC, but the damage has already been done, or (2) Support file encryption/decryption only, so that we can encapsulate all of that.

**Comment by sarciszewski** [comment]
Could we drop the HMAC and use `aes-128-gcm` mode? Would this enable better support for streaming?

**Comment by defuse** [comment]
That wouldn't really help, since the problem is in the API we would have to make available, and the APIs we have to use. 

The problem inherent in streaming is that you can only authenticate once you've seen the entire ciphertext, so if you don't want to hold all of the plaintext in memory, you have to return unauthenticated plaintext to the user, which is a security risk even if the last decryption call fails (because either the user will ignore it or the damage will have already been done if the plaintext was being piped to `/bin/sh`).

You can authenticate in "chunks" (see Minilock) but that's complicated and still allows the ciphertext to be truncated.

These problems exist no matter which MAC or AEAD we use.

I don't think there is a "hard to misuse" API other than the input being two parameters: the file path to the plaintext and the file path to the (to-be-created) ciphertext. The only point of streaming is to save RAM (this isn't a network encryption library), and assuming the plaintext isn't already in RAM (in which case saving RAM doesn't matter), it must be on disk, either in a database or a file. We can ignore the database case for now and solve the file case.

But we have to be careful and ensure:

- No plaintext/ciphertext is ever written to a different disk/partition than the user intended (for secure delete purposes).
- If the encryption/decryption fails, the output file should be something predictable (e.g. not exist, which is different than a file of 0 bytes).
- A local attacker can't modify the plaintext/ciphertext file after or during its creation.
- File permissions are such that a local attacker can't just read the plaintext file.
- Probably 100 other things I'm not thinking of right now.

Obviously, making a "very hard to misuse" API for this is going to be quite a challenge, as the right solution requires intimate knowledge of the environment and use case.

**Comment by defuse** [comment]
We should encapsulate the storage mechanism, and then instead of making the client call us, we should call (and runtime test!) the client. So we would provide some interface, say `CryptoDataStore`, which the client would implement. Then, the client would pass our encrypt function us two instances: One containing the plaintext, and one containing the ciphertext that we write to. We could provide reviewed implementations for the Linux filesystem and MySQL databases. Then the person over in #38 could pass a `LinuxFileCryptoDataStore` as the first argument and a `MySQLCryptoDataStore` as the second argument.

But what would the `CryptoDataStore` interface be? It can't be a simple `read()` and `write()`, otherwise we have the same problem as above. We'll need some kind of "temporary storage" before we "finalize" the data into the actual output.

**Comment by defuse** [comment]
If we get this API perfect, then maybe libsodium could adopt it!

**Comment by defuse** [comment]
**Here is the number one rule for this ticket:** Whatever we end up with must be user-tested. By user-tested, I mean using 10-20 developers of varying experience to compare it to the null hypothesis (the "obvious" way to do streaming that we're trying to avoid).

**Comment by defuse** [comment]
1. We take 3 parameters: Input, Temporary, and Output
2. We apply the crypto transform on the Input into Temporary
3. Upon failure, call `Temporary.destroy()` and signify failure.
4. Upon success, transfer Temporary into Output, call `Temporary.destroy()`, then signify success.

For Linux files, (4) would be just a `mv` within the same filesystem, and would be fast. For file-to-database, Temporary would be a file, and (4) would require an additional (second) copying. Another downside is that we're making two copies of the plaintext instead of just one (thus making it non-obvious to the user what devices their plaintext has been spread to).

Anyone else have any better ideas?

**Comment by zookoatleastauthoritycom** [comment]
I like the API in https://github.com/defuse/php-encryption/issues/39#issuecomment-73328975

**Comment by sarciszewski** [comment]
What do you think about this process?

1. Process the file in chunks (e.g. 512 KiB).
2. Upon any encrypt/decrypt operation, start with `hash_init()` and `hash_update()` with the MAC of each successive chunk.
3. Only store the final hash at the end?

**Comment by defuse** [comment]
@sarciszewski Yes, that's (something like) what we would do, similar for encryption and decryption, but the problem is making a hard-to-misuse API on top of that.

**Comment by zookoatleastauthoritycom** [comment]
I think there may be different, and in fact incompatible (!) use-cases in mind here:

1. Easy partial reads: I can easily read a few bytes out of a larger file (potentially *much* larger), while being assured that the bytes that I did read were the correct bytes, even in the case that a malicious attacker was attempting to trick me into accepting the wrong bytes.

2. Avoid truncation attacks: I can easily read the entire file, and cannot easily be fooled into accidentally reading only a subset of it, while thinking that I've read the entire thing.

These are approximately the opposite of each other.

I think looking at specific API proposals illustrates this. For example, you could have an API modelled on the C stdio API, with a function named read() that takes a file handle and a length to read, and then returns 0 to indicate that the end of the file has been reached, or a special value (it is -1 in the C stdio API) to indicate that some error prevents the read from completing.

This is compatible with use-case 1, but not so great for use-case 2, because a programmer might handle the error case as though it were the "we've reached the end of the file" case. This is especially common when the error case doesn't happen in testing, since some programmers decide what cases to handle by testing instead of by reading the docs. If the programmer does that, then the attacker can fool that code into accepting truncated files as though they were complete files.

On the other hand, consider an API like the one proposed by Taylor in https://github.com/defuse/php-encryption/issues/39#issuecomment-73328975, which either gives you the complete file contents or an error condition (*not* a zero-length file contents). This is great for use case 2, but completely useless for use case 1.

**Comment by paragonie-scott** [comment]
After #57 is reviewed and merged, I'll create a PR to add stream encryption/decryption (e.g. files). :)

**Comment by paragonie-scott** [comment]
**PoC here, no GTFO required**: https://github.com/paragonie-scott/php-crypto-stream

So, I'll probably need to do some tweaking and cleanup before it's production-viable, but this should facilitate file encrypting/decrypting with whole-file MACing. I call it `LowMemory` because it is my hope that the actual memory usage should remain somewhat constant.

**Comment by defuse** [comment]
This is done in v2.0. I'm happy with the API it provides (but still haven't reviewed the crypto code closely enough).
