### ISSUE TITLE
Short encryption string

### ISSUE THREAD

**Issue by ReactionCode** [defuse/php-encryption#406]
Hi.

Actually I'm encrypting urls params for email campaigns with Defuse because one of the params is the customer email.

So a raw link:
https://domain.com/link/?id_campaign=1&id_shop=1&id_customer=2&email=neuser%40test.com&id_link=0

Will be encrypted to:
https://domain.com/link/?def50200880e4f94f9f1ad133fa33c2bca4ee26c3c3057c622e3a142d008983cc41697c6192a4026e4b1ae7593b75a613dd483906f13f848c59588bb5a2289b635aaa9a7039ed604e10b13ed23422bad4c20851f8fe6937bcc651993d7f077aae1a14682714ed7e9756837e29012119f172a7610e2e10405a5918d913a5a7fb61dd85feadbd786c9f20731466f3ef17caa809a8588b578e3c4cca1

It's possible to short this string?

The methods to handle the encryption are:

    public static function createRandomKey()
    {
        // create new key object
        $key = Key::createNewRandomKey();
        return $key->saveToAsciiSafeString();
    }

    public static function encryptUrl($key, $url)
    {
        $key = Key::loadFromAsciiSafeString($key);
        return Crypto::encrypt($url, $key);
    }

Best regards.
Javier.

**Comment by paragonie-scott** [comment]
If you haven't already read [this page](https://paragonie.com/blog/2015/09/comprehensive-guide-url-parameter-encryption-in-php), it's worth taking a minute to read and understand. Short, encrypted URLs are dangerous in general, and the popular implementations (eg. Hashids) are not cryptographically secure.

Furthermore, an obfuscated URL does not obviate the need for access controls.

> Is it possible to shorten the string?

Somewhat. Return raw binary instead of hex, then use [paragonie/constant_time_encoding](https://github.com/paragonie/constant_time_encoding) (specifically, `Base64UrlSafe::encodeUnpadded()` and `Base64UrlSafe::decode()`) and you can shave your URL parameter from 310 characters to 207.

**Comment by risototh** [comment]
And with even longer URL, you can first deflate the data with gzdeflate(), then encrypt, and then encode with base64 mentioned above. And of course, at the other side, same workflow, but in opposite direction.
