### ISSUE TITLE
Provide a way to set the encryption algorithm

### ISSUE THREAD

**Issue by teo1978** [defuse/php-encryption#410]
I'm astonished to find out that there's no way to change the encryption algorithm to use.

Core::CIPHER_METHOD should be a configurable parameters rather than a constant.

**Comment by paragonie-scott** [comment]
End users not being able to change the encryption algorithm is expected behavior.

Part of what this library does is make secure choices for you, rather than expect you to make them yourself. The difference of security margin between AES-256-CTR and Salsa20 isn't that interesting in practice, but the difference between AES-256-CTR and Blowfish-ECB definitely is.

The security of this library can be easily guaranteed for [the algorithms selected](https://github.com/defuse/php-encryption/blob/master/docs/CryptoDetails.md). Any deviation from these hard-coded algorithm choices may lead to a reduction in security.

In case this sounds crazy, please be aware that the trend on modern cryptography APIs is to do what we're doing here: Define "one true ciphersuite" for a given version of a given protocol, and then issue newer versions as needed, rather than allowing runtime building block negotiation. In other words, we're trying to avoid [reasoning by lego](http://www.cryptofails.com/post/121201011592/reasoning-by-lego-the-wrong-way-to-think-about).
