### ISSUE TITLE
Question about txt file 

### ISSUE THREAD

**Issue by Daksh14** [defuse/php-encryption#440]
This may be a dumb question, sorry for that but,
```php
<?php
use Defuse\Crypto\Key;

function loadEncryptionKeyFromConfig()
{
    $keyAscii = // ... load the contents of /etc/daveapp-secret-key.txt
    return Key::loadFromAsciiSafeString($keyAscii);
}
```
I was told in the tutorial that I have to load the contents of  /etc/daveapp-secret-key.txt in there. My question is, what if anyone accesses that text file through URL. Will they be able to generate my key? For example. If they typed `localhost/daveapp-secret-key.txt` then? I'm asking this because I'm restricting my PHP and server to go out of the root folder for security reasons.

**Comment by Kaulkwappe** [comment]
Hi Darksh14,

there are no dumb questions, especially when it comes to security! It is a complex thing.

You said you would store the key in **/etc/*** which is a non-public internal directory from your Linux distribution. This directory is generally not accessable to the user, because the root directory for the according virtual host in Apache2 is locked with this directive:

`DocumentRoot /var/www/vhosts/example.com/web`

As long the web server has no security holes a user won't be able to change this document root. However, the web servers itself is not restricted to this directory. That said, users could gain access by using potentially security holes in your application. When there are no such security holes, e.g. using non-filtered user input for including or reading files or executing shell commands, this file won't be readable due the HTTP(S) connection from the user.

You may also want to set the permissions of this file exclusively to the web server user, in Apache2 this would be **www-data**:

```
chown www-data:www-data /etc/daveapp-secret-key.txt
chmod 0400 /etc/daveapp-secret-key.txt
```

This will let the webserver read the file, but prevents it from changing or deleting. If you want to allow the webserver to change the file, chmod **0600** would be your way.

However, this does not prevent users to use exploits which are opened by other web applications because they also use **www-data*.

**Comment by Daksh14** [comment]
Exactly. I am actually saving the key on another server and loading it from there using a secure API. This helps a lot thanks.

**Comment by Kaulkwappe** [comment]
Additionally you can use on the server, where the key is, a custom TLS port:

```
/etc/apache2/ports.conf

<IfModule ssl_module>
	Listen 443
	
	# Custom port
	Listen 8030
</IfModule>
```

Then you can restrict connections to this port to the IP address of the servers which are allowed to use the API:

```
# Block web traffic on internal port
iptables -A INPUT -p tcp --dport 8030 -j REJECT --reject-with tcp-reset

# Allow web traffic only for specific ip addresses
iptables -I INPUT -s {CLIENT_IP_ADRESS} -p tcp --dport 8030 -j ACCEPT
```

However, this would also not prevent from reverse engineering and getting the key if you run any untrusted web application on your clients server.

**Comment by defuse** [comment]
Thanks for answering, @Kaulkwappe! 

I'd advise against using source-address filtering (worst case all you have to do is get lucky and guess some TCP parameters). If server A is pulling the key from server B and it will exist in server A's memory at any point in time, then you might as well just store it as securely as possible on server B and avoid the risk of sending it over the network. Or if it has to be fetched from elsewhere, use a mutually-authenticated TLS connection. Server A needs to know it's getting the real key, not e.g. an attacker trying to give it the all-zero key; server B needs to know it's really giving the key to server A, not an attacker). You could also keep the key on server B and expose a secure API for operations that need the key.

**Comment by Kaulkwappe** [comment]
Thank you too Sir!

> I'd advise against using source-address filtering (worst case all you have to do is get lucky and guess some TCP parameters to get around it).

I'm not sure what do you mean by that exactly. Do you refer to my firewall rule? This is only an additional barriere to the API which prevents from connecting to it at all from untrusted sources.

**Comment by defuse** [comment]
Yeah, on top of another way of securing the API it's not a bad idea.

It can be bypassed if (a) you're on the local network (mess with ARP / layer 2 to give yourself the allowed IP), (b) if you can intercept the traffic between the allowed IP and the API, or (c) you might be able to send stuff to the API (if it weren't otherwise authenticated) if you forge a SYN, guess the parameters the API's SYN-ACK, then forge an ACK with some data.

**Comment by Kaulkwappe** [comment]
Thanks for clarifying that!
