### ISSUE TITLE
Error thrown but decrypt still working fine

### ISSUE THREAD

**Issue by smik3** [defuse/php-encryption#443]
Getting the below error when decrypting a mySQL result, however the function is still processing the string fine - I can view the unencrypted result with no issues.
I haven't changed the ciphertext but the site has been migrated to a new server/domain, could this have caused the issue? Would generating a new key and decrypting/re-encrypting the values help?

`Got error 'PHP message: PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\WrongKeyOrModifiedCiphertextException' with message 'Ciphertext is too short.' in phar:///home/storm/sites/iwall-events/public/app/vendors/defuse/defuse-crypto.phar/src/Crypto.php:223\nStack trace:\n#0 phar:///home/storm/sites/iwall-events/public/app/vendors/defuse/defuse-crypto.phar/src/Crypto.php(68): Defuse\\Crypto\\Crypto::decryptInternal(NULL, Object(Defuse\\Crypto\\KeyOrPassword), false)\n#1 /home/storm/sites/iwall-events/public/app/dashboard/public/index.php(25): Defuse\\Crypto\\Crypto::decrypt(NULL, Object(Defuse\\Crypto\\Key))\n#2 {main}\n  thrown in phar:///home/storm/sites/iwall-events/public/app/vendors/defuse/defuse-crypto.phar/src/Crypto.php on line 223\n'`

**Comment by paragonie-scott** [comment]
Encoding issues, most likely. Make sure you're storing hex-encoded data, not raw encrypted bytes.

**Comment by smik3** [comment]
I'm using the default for Crypto::encrypt($plaintext, Key $key, $raw_binary = false) 
ie
only supplying $plaintext and $key variables.
Should I be explicitly setting the $raw_binary flag?

**Comment by Kaulkwappe** [comment]
Are you sure you're database type (e.g. VARCHAR or TEXT) isn't cropping the encrypted ciphertext?

**Comment by smik3** [comment]
Considering the type was set to longtext, I doubt that. The error only seems to be logged on the initial page load, so if the page is refreshed later in the day it doesn't add to the error log.

**Comment by Kaulkwappe** [comment]
Then you may apply no ciphertext at all, due to an error with your authentication system, e.g. if you redirect non-authenticated users with the PHP header() function without directly using exit() after the redirection instruction. That would cause all the code after this redirection instruction to be executed altough the user don't see that.

But that is just an assumption :)

**Comment by smik3** [comment]
Hmm, that could be a possibility.. however I'm not using the library to authenticate users, just to display their profile information in a sidebar once they've logged in so there's no redirection. it just seems odd that the function is throwing an error but then still decrypting the $ciphertext so that it can be printed as a $plaintext.

**Comment by Kaulkwappe** [comment]
> just to display their profile information in a sidebar once they've logged in so there's no redirection.
But when they open the profile page – where the decryption is done in the background –, how do you redirect them to the login page then?

**Comment by smik3** [comment]
Not a profile page - just a side bar in the home page. This is after they've logged in

**Comment by defuse** [comment]
If `decrypt()` throws a `Defuse\Crypto\Exception\WrongKeyOrModifiedCiphertextException` it can't have returned a value, because the function call exited by way of the exception throw. This issue is quite old so I suspect it was worked around or resolved in some way, if it's still a problem and you can isolate a test case that shows this library misbehaving in some way please re-open the ticket.
