### ISSUE TITLE
Decryption of text bigger than 65535 characters is not possible

### ISSUE THREAD

**Issue by Betacarotin** [defuse/php-encryption#458]
There is no handling of texts with more than 4000 characters in plain mode, which leads to more than 65535 characters in encrypted mode. The text is encrypted but can´t be retrieved again. 

What can I do to encrypt almost endless long texts? Wouldn´t it be good to implement a "Auto-chunk" and "De-chunk" function into your encryption library? Right now its a trap- because it will encrypt the input but never decrypt it again =>Data loss

**Comment by scottarc** [comment]
Are you storing your data in a MySQL `TEXT` field?

**Comment by Betacarotin** [comment]
Yes! 
I am saving text inputs from users in a database. 
These textinputs are basically strings with some html. 
I wish to to encode them, so that its not possible for everyone with access to the database to see what the users have written. 
So- thats why I store text from my users form in a MySQL TEXT field

Encryption of names, mails, numbers is all fine, its just the text… that wont go through. 
/Michael

**Comment by scottarc** [comment]
This isn't actually a bug with this library, your database is silently truncating your TEXT fields at 65535 characters. If you truncate data, it will not be decryptable because the authentication tag is different.

1. Turn on Strict Mode for your database.
2. Change your `TEXT` to a `MEDIUMTEXT` (or larger field) to exceed the 65535 limit.

**Comment by Betacarotin** [comment]
I am so sorry! 
Thanks, now it works!
