### ISSUE TITLE
'Bad version header' decryptResourceInternal method in File.php

### ISSUE THREAD

**Issue by killianb-cnrs** [defuse/php-encryption#460]
Hi,

I am storing large files which must be downloadable by users, that's why I am using the File class rather than the Crypto class as recommended. However, I still have the same error : 'Bad version header' WrongKeyOrModifiedCiphertextException. This is not a key issue because when I use Crypto :: decrypt with small files it works fine. 

Someone have an explanation please? Thanks.

`File::decryptFile(
            '/var/www/upload/'.$document->getFilePath(),
            '/tmp/'.$document->getNomFichier(),
            $this->key
        );`

**Comment by defuse** [comment]
Sorry for the slow response! Are you sure that what you're decrypting (i.e. the contents of `'/var/www/upload/'.$document->getFilePath()` is a valid ciphertext produced by the library? All ciphertexts produced by this library begin with the bytes `"\xDE\xF5\x02\x00"`, and the error is saying that the file does not begin with those bytes, so possibly (1) something went wrong with the encryption that it didn't produce the correct result or (2) the file is not a ciphertext.

Would it be possible to write a short sample PHP script that reproduces the problem?

**Comment by killianb-cnrs** [comment]
Thank you for your answer. Yes, my document is a valid ciphertext produced by the library. I check bytes and it's ok.

`
$this->key = Key::loadFromAsciiSafeString($key);
`

`File::decryptFile(
            $document->getFilePath(),
            '/tmp/'.$document->getNomFichier(),
            $this->key
);`

With this method, that works perfectly (with small files) :

`$content = Crypto::decrypt($file->getContent(), $this->key);`

Maybe i'm missing something but i don't see what and indeed the error message seems to mention an encryption problem but why.

**Comment by defuse** [comment]
Is it possible to write a single script that completely reproduces the problem (e.g. generates the encrypted file, attempts to decrypt it, and fails)? That would help me debug the problem.

The `Bad version header` error message happens if and only if the first 4 bytes of the file don't match the expected version header: https://github.com/defuse/php-encryption/blob/147b536b684c3760fcf8d85d9ce7418b3f0e4ed2/src/File.php#L468-L473. Is it possible that something's encoding/modifying/truncating the ciphertext file to screw up the header bytes?

Thanks!
