### ISSUE TITLE
Lifetime

### ISSUE THREAD

**Issue by LocalHeroPro** [defuse/php-encryption#483]
> This library is expected to remain stable and supported by its authors with security and bugfixes until at least January 1st, 2022.

What happened after that date? That library will be abounded?
Did you guys developed something brand new?

**Comment by defuse** [comment]
Normally, every year I bump the date in the README to indicate that it's still supported. The idea being, if I ever disappear or decide to stop supporting the repo without updating it, people will automatically be warned by this text.

I see that it's causing some worry and anxiety around the library, so I think this time I'll bump it a couple years so that it's always at least 1 year away from the date.

Thanks for the reminder!
