### ISSUE TITLE
Safe to change static encryption keys?

### ISSUE THREAD

**Issue by davidcroda** [defuse/php-encryption#49]
Hello,

TLDR: is it safe to change the two constants

    const ENCRYPTION_INFO = 'DefusePHP|KeyForEncryption';
    const AUTHENTICATION_INFO = 'DefusePHP|KeyForAuthentication';

I am concerned about a situation where an attacker has compromised the database, and therefore has access to the encrypted data and ivs.  In that situation, if they know the secret used for encryption they can decrypt the data.  I would rather not use a hard coded secret that is constant across all copies of this library.

I see a giant comment saying not to change any constants, however these seem different then the others in that they don't change the workings of the encryption at all.

If it *is* unsafe to change these, how do you recommend addressing my issue above? Am I just applying the library wrong?

Thanks

**Comment by defuse** [comment]
Those constants are not encryption keys, they are strings used in the info parameter to HKDF to differentiate the authentication key from the encryption key. You provide the library with a random 16 bytes (the `$key` parameter), and the library splits it into two keys (one for authentication and one for encryption) using those strings. Those strings being public does not affect security.

Perhaps it is a bit misleading, since they say "KeyForEncryption" and "KeyForAuthentication", but they are not themselves keys, they are descriptions of the keys HKDF will be generating.

**Comment by sarciszewski** [comment]
These constants aren't used for encrypting/decrypting data. They're used by `HKDF` to split your encryption key into two keys (one for encryption/decryption, the other for signing/verifying the ciphertext with an HMAC).

Changing them won't increase your security. If an attacker can compromise your database, they can also probably compromise your filesystem. (`SELECT somestring INTO OUTFILE /var/www/shell.php`)

Changing them *will* prevent interoperability with other applications that use this library, and will create merge conflicts if you ever need to upgrade (e.g. if a vulnerability is discovered in the current iteration of Crypto.php).

**Comment by defuse** [comment]
@davidcroda Could you think of anything we could do to make that more obvious? Would a comment like

`// Constants used to split the key into authentication and encryption keys.`

have helped?

Thanks.

**Comment by davidcroda** [comment]
Thanks for the info guys, I should have checked more closely at where they are actually used.

@defuse that may have helped.  It sounds like this may be an issue you have had before, if so you could probably put something explicit like "// Despite the name, these are NOT encryption keys . The only kind of confusing thing is the value of the constants, however it sounds like that cannot be changed at this point.

@sarciszewski in my situation the database is remote and has no access to the application files, so I was hoping to have an additional layer of security with the separate keys in the database as well as filesystem.

I am probably missing something, but it seems like the only other way to achieve this right now would be to use a single, constant key in the source to encrypt everything (which doesn't sound particularly safe. I don't think you are supposed to encrypt multiple things with the same key).

**Comment by sarciszewski** [comment]
> the database is remote and has no access to the application files

Massive :+1: on hardware separation

**Comment by sarciszewski** [comment]
> (which doesn't sound particularly safe. I don't think you are supposed to encrypt multiple things with the same key)

That depends on your threat model. Anyone who gets your key can decrypt everything. In other words, using the same key offers no forward secrecy; for that, use something like libsodium to negotiate ephemeral symmetric encryption keys from a public key exchange authenticated by long-term (pinned) keypairs.

Since the library uses CBC mode with a random IV, the key reuse isn't an issue for just storing encrypted data in a database.

**Comment by davidcroda** [comment]
> Since the library uses CBC mode with a random IV, the key reuse isn't an issue for just storing encrypted data in a database.

Ok, fantastic. That's exactly what I needed to know.  I figured I was missing something.

Thanks very much for the answers and for the excellent library!
