### ISSUE TITLE
Encrypt in PHP, decrypt in nodejs and vice versa

### ISSUE THREAD

**Issue by yellow1912** [defuse/php-encryption#64]
Hi,

I would like to ask a stupid question: I would like to send a crypted message between nodejs and php applications and I would love to use this lib. However, I'm unsure as how I should decrypt the encrypted message in nodejs and vice versa. As I'm a total beginner in this, any pointer would be extremely appreciated.

**Comment by paragonie-scott** [comment]
> I would like to ask a stupid question

I don't believe your question is stupid.

> I would like to send a crypted message between nodejs and php applications and I would love to use this lib. However, I'm unsure as how I should decrypt the encrypted message in nodejs and vice versa.

I don't believe there is currently a Node.js library that formats message in the same protocol or uses the same HKDF salts for splitting keys.

> As I'm a total beginner in this, any pointer would be extremely appreciated.

I see. Well, maybe we can discuss writing a compatibility library for Node.js after we handle #39 and #34 sufficiently? (I'd like to tag @joepie91 on this, since his knowledge of Node.js security far exceeds mine.)

**Comment by joepie91** [comment]
Reporting in :)

**Comment by yellow1912** [comment]
That sounds like a great start, I'm neither a nodejs expert (just beginning to learn it due to work requirement) nor a security expert. But if there is anything that I can help with this issue I will be glad to :)

**Comment by pnowosie** [comment]
I'd be more than happy to help as well. Easy to use, secure encryption lib compatible between popular stacks - sounds great for me ;)

**Comment by paragonie-scott** [comment]
If we're going to make it stack-agnostic, we'd probably need to finalize the message syntax first w.r.t. #34

**Comment by adamcaudill** [comment]
*Slightly OT*

I've been working on [SmartEncryption](https://github.com/adamcaudill/SmartEncryption), a secure-by-default crypto library for .NET - @defuse and I had talked about trying to make them compatible, so there's already been some talk of taking this beyond PHP. The main stumbling block was my goal of using AES-GCM, which turns out to be problematic in PHP (one of the goals for SmartEncryption is to serve as a way to introduce modern crypto to the .NET world).

There is an open ticket to add AES-GCM to libsodium which may be useful, though unknown if it'll happen: https://github.com/jedisct1/libsodium/issues/234

Taking this beyond PHP seems to be a very good idea to me. Developers should have libraries available that do the right things for them, without the need for them to understand the crypto engineering involved. To be really successful, interoperability will have to be addressed - so taking this to a standardized design that can be implemented for other platforms seems like the next logical step.

**Comment by paragonie-scott** [comment]
In the libsodium side of things, there's a discussion going on to [create a PDO-like class abstraction for cryptography](http://news.php.net/php.internals/86396) that's pluggable and supports multiple backends (openssl, libsodium, etc). That's probably more directly orthogonal to SmartEncryption than the efforts here.

Since the purpose of this library is to work without needing PECL extensions (e.g. libsodium), I don't think we can make AES-GCM a reality for this project.

**Comment by adamcaudill** [comment]
@paragonie-scott On the GCM issue, I had already accepted that it created a conflict in goals that make compatibility impossible (at least without one side changing goals), but I thought it worth bringing up that there had already been some discussion of taking this effort beyond PHP.

**Comment by defuse** [comment]
(Not including this in v2.0)

**Comment by paragonie-scott** [comment]
Once v2.0 is done, I can work on a compatible npm module (which can in turn be used in Electron apps).

**Comment by defuse** [comment]
I want to focus this project on compatibility with itself inside PHP. If you want compatibility across languages, then I recommend libsodium (or Halite). I think it would be a mistake for this project to compete with libsodium that way. If we did, there would be two common ciphertext message formats floating around: the php-encryption one and the libsodium one. That would actually make overall compatibility *harder* since there's a smaller chance whatever you want to be compatible with chose the same one as you.

So, even though this library would see more use if there were officially-supported implementations in other languages, I'm going to make the altruistic decision to not support any. Others are, of course, free to make other-language implementations, but I won't make an extra effort to support them.

@paragonie-scott: It's probably better to make a Halite wrapper for node.js, that would be cool!

In the long term, I hope languages start to support the libsodium/Halite formats and API natively, like they support OpenSSL today. Having two popular ciphertext formats would make it harder for language design committees to unanimously decide on which one to support.
