### ISSUE TITLE
ASCII Safe Encoding

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#76]
Should we have an option to allow ciphertexts to be encoded in an ASCII-safe way? I'm getting a lot of issues (like #59) and emails where the binaryness is leading to unintentional ciphertext corruption (e.g. going through HTTP post, getting inserted into HTML, etc.). Maybe ASCII-safe ciphertexts should be the default?

**Comment by defuse** [comment]
Note that this would *not* solve the problem of MySQL truncating things. Maybe this is better solved via documentation and a FAQ?

**Comment by paragonie-scott** [comment]
We can make it the default for v2.0.0 easily, and then have a flag for "I want raw binary".

Following this, we have two ways we can go:

1. Hex encode the ciphertexts. We already have `binToHex()` and `hexToBin()` so this is easy. (Thanks @CodesInChaos and @jedisct1 for the libsodium implementation that I referenced!)
2. Use an alternative RFC 4648 encoding scheme (base32, base64) while not introducing side-channels.

Option 1 is easy and most of the work is done for us, and it's consistent with `hash()`.  
Option 2 saves space in the output while still being 100% ASCII-safe.

**Comment by NicolasCARPi** [comment]
Hello, I have to store my passwords as text, because the way I did my config table, it will not accept binary blobs. It says on the file that using bin2hex or base64_encode is bad as it introduces side-channels. Until you guys implement a secure way to transform binary to something you can put in text, I'll base64_encode/bin2hex I guess. 
Can you tell me what are those «side-channels» so I can evaluate the risk ?

Relevant twitter discussion : https://twitter.com/DefuseSec/status/432577681092116480

**Comment by NicolasCARPi** [comment]
Wait, isn't binToHex and hexToBin in the class already good for that purpose ??

**Comment by paragonie-scott** [comment]
#78 now defaults to hex encoding. I don't think there's much point adding a more complicated encoding scheme; if anyone wants, they can specify raw and `base64_encode()` it.

**Comment by defuse** [comment]
Excellent. Closing.
