### ISSUE TITLE
Automatic library update check

### ISSUE THREAD

**Issue by TheStefan** [defuse/php-encryption#83]
First of all, I like this lib very much. I am new to github and this might be a stupid idea or not appropriate to this repo. But i was thinking if an automatic update check would be a possible feature to include. My idea is that the library will periodically check for an update of the library. When the library found a update of itself it could do various things, like automaticly update or block itself untill the lib is updated. This feature may reduce the amount of unsafe versions used in public in case of a security bug. #34 might be required. Maybe this could be on the roadmap for future versions?

However I do understand the developper or webmaster itself is always responsible for making a website safe.

**Comment by paragonie-scott** [comment]
An immediate and simple solution: you can use [composer](https://getcomposer.org) to install/update this package. Then when you run `php composer.phar update` it will grab the latest version.

**Comment by defuse** [comment]
I'm going to say no to this feature, because it adds a huge new attack surface. Anyone with my code signing keys could secretly and invisibly form a botnet of servers using the library. I don't want to have that kind of power, and nobody should trust me with it.

For a crypto library this size, it's reasonable to expect us to get it right the first time and never have to push a security fix. We're talking about hiring an external auditor in #90.

Also, using composer to update is a good idea.
