### ISSUE TITLE
Roadmap / timeline

### ISSUE THREAD

**Issue by PeeHaa** [defuse/php-encryption#88]
Any roadmap / timeline for a new release?

Not using namespaces is kinda annoying for me.

**Comment by paragonie-scott** [comment]
I proposed a roadmap in https://github.com/defuse/php-encryption/issues/71 and https://github.com/defuse/php-encryption/pull/78 has a lot of the drastic changes that I'd propose for 2.0.0.

I don't anticipate much pushback on the roadmap, but the timeline is uncertain.

@defuse hasn't had the free time to look at my changes in the past couple of weeks (really super busy) and he's not going to just merge them (he's *very* careful with code).

Even if my PR is merged without additional concerns being raised, I can't guarantee that 2.0.0 will be tagged immediately afterwards. Especially if he decides that, yes, `random_compat` is a desirable dependency for 2.0.0 and that's not stable because of a PHP 7 internals decision with exceptions and errors.

So, we have a proposed roadmap that I think @defuse will approve, but the timeline is unknown.

**Comment by paragonie-scott** [comment]
Well, now that random_compat is stable, that's one less headache to deal with.

**Comment by defuse** [comment]
I'm going to close this issue since it doesn't have a clearly-defined goal. (By the way, thanks for the namespace feedback! v2.0 is in a namespace)
