### ISSUE TITLE
AES 256 and donations for audit?

### ISSUE THREAD

**Issue by SebiTimeWaster** [defuse/php-encryption#90]
this is not so much an issue but two questions:

1. why not AES 256? i know that AES 128 is secure and that using a 256 bit key length would have a performance impact, but i could imagine that users knowing absolutely nothing about cryptography (so basically everyone, even if they think they know something) could be repelled from using php-encryption because they think it is not secure enough for using 128 bit keys.

2. could it be helpful to setup a donation button/website/whatever to collect money for a security audit? i have no clue how much an audit would even cost or if it would be difficult to do since the underlying language would have to be evaluated, too?

**Comment by paragonie-scott** [comment]
See #35.

I think raising funds to hire someone who isn't me or Defuse to audit this library is a good idea.

**Comment by paragonie-scott** [comment]
Sidenote: We could change it to use AES-256 in version 2, very easily.

**Comment by xandersherry** [comment]
For whatever it's worth, I'd be opposed to changing to AES-256.  This library should be an implementation of best practices, not a collection of compromises to cater to common misconceptions. Just my two cents.

**Comment by paragonie-scott** [comment]
[256-bit AES keys are fine](https://gist.github.com/tqbf/be58d2d39690c3b366ad). So are 128-bit keys.

I was just saying we could do it, not that we should.

**Comment by paragonie-scott** [comment]
So, I'd like to revisit the "collect money for a security audit" point. 

Taylor's disqualified from auditing it, because he's the author. I'm disqualified, because I'm the co-author. A lot of infosec companies are charlatans (i.e. the ones that failed [RandomLib](https://github.com/ircmaxell/RandomLib) because one of its many inputs was `mt_rand()`). Some companies have audited applications, only for Taylor or myself to come along and find crypto flaws (padding oracles and timing attacks) in it.

So, what I would propose is this:

1. Let's get version 2 finalized.
2. Identify individuals or companies qualified to do a full, formal audit on the library.
3. Figure out what our fundraising benchmark should be.
4. Try and raise it, with someone (e.g. myself) willing to step in financially if we don't raise enough to cover the audit, or audit goes over budget.

And then we can say, "Yes, we've been audited."

**Comment by defuse** [comment]
Having an audit on the horizon makes me much less worried about any security vulnerabilities that may have been introduced by the version 2 changes.

**Comment by defuse** [comment]
-and that motivates me to get around to looking at them and merging them sooner. :-)

**Comment by RichardCheung** [comment]
It is true that if I change the key size
```
// src/Cypto.php
const KEY_BYTE_SIZE = 32;
```
the library will work in AES-256-CBC?

**Comment by defuse** [comment]
@RichardCheung: No, it won't. The runtime test vectors will fail (and maybe other things).

**Comment by paragonie-scott** [comment]
@RichardCheung Why do you want to change the key size?

**Comment by defuse** [comment]
Everything in this ticket has its own ticket so I'm closing it.
